### ISSUE TITLE
Lint errors not showing in Sublime Text and Atom

### ISSUE THREAD

**Issue by jonsaw** [txchen/eslint-plugin-riot#3] opened 2016-02-24 03:33 UTC
Lint errors show up fine in the Terminal when we run:

```
./node_modules/.bin/eslint ./src/*
```

But does not show with SublimeLinter (for Sublime Text) or linter-eslint (for Atom).

**Comment by txchen** [comment] 2016-02-24 04:29
I am not using sublime, but I will take a look at atom. Previously it worked in atom, then I switched to use VScode.

**Comment by txchen** [comment] 2016-02-24 04:53
Just had a test, it works in my atom with some tuning.
I personally use .html as file extension for my riot tag files. Then in atom linter-eslint config, check the `Lint HTML Files`. 
It will work as expected.

![image](https://cloud.githubusercontent.com/assets/713074/13275966/6f516210-da6f-11e5-9a0c-46aaee957764.png)

**Comment by txchen** [comment] 2016-02-24 04:54
For sublime, I think it is due to same reason: the editor plugin should lint the tag files. By default they lint *.js and *.es6, but not *.tag or *.html.

Close this issue.

**Comment by jonsaw** [comment] 2016-02-24 04:55
Changed the filename to '.html'. Looks like linting is working but now getting the following error:

```
Error: ESLint crashed: Cannot read property 'length' of null
```

**Comment by jonsaw** [comment] 2016-02-24 04:59
Image:
<img width="1063" alt="screen shot 2016-02-24 at 12 57 59" src="https://cloud.githubusercontent.com/assets/1572333/13276063/5954fcec-daf6-11e5-968e-735903a679da.png">

**Comment by txchen** [comment] 2016-02-24 15:56
@jonsaw could you please share your package.json? I'd like to see the eslint package versions.

**Comment by jonsaw** [comment] 2016-02-26 02:52
package.json

```
{
  "name": "demo",
  "version": "0.0.1",
  "scripts": {
    "build": "webpack --config webpack.config.js"
  },
  "dependencies": {
    "riot": "^2.3.15"
  },
  "devDependencies": {
    "babel-core": "^6.5.2",
    "babel-eslint": "^5.0.0",
    "babel-loader": "^6.2.3",
    "babel-polyfill": "^6.5.0",
    "babel-preset-es2015": "^6.5.0",
    "eslint": "^2.2.0",
    "eslint-config-airbnb": "^6.0.1",
    "eslint-plugin-react": "^4.0.0",
    "eslint-plugin-riot": "^0.1.4",
    "file-loader": "^0.8.5",
    "riotjs-loader": "^1.2.0",
    "webpack": "^1.12.13"
  }
}
```

**Comment by txchen** [comment] 2016-02-27 01:56
ok. It might be due to eslint v2. I will upgrade my project and verify. Thanks for the information.

**Comment by txchen** [comment] 2016-02-27 04:38
@jonsaw I just did a test with atom + latest eslint-atom plugin + latest eslint. It works well on my machine.

Code is here: https://github.com/txchen/feplay/tree/gh-pages/riot_webpack

I suggest you to call eslint in CLI to see the result, if it works well, but not in the editor, I'd say it is editor plugin's issue. I don't use sublime text, so cannot help to test it.

**Closed as completed by txchen** 2016-02-27 04:38 UTC

**Comment by txchen** [comment] 2016-02-27 04:39
As  you can see, I have a npm script in my package.json:

`"lint": "eslint --ext .js,.es6,.html src/*"`

I run `npm run lint`, and I can confirm that eslint-plugin-riot works well.

**Comment by throrin19** [comment] 2016-04-08 14:11
How to add the support of `.tag` file on atom and sublimeText ?

**Comment by txchen** [comment] 2016-04-08 22:56
@throrin19 that is limited by the editor plugin, not this plugin. If editor plugin don't call eslint on .tag file, there is no way to do that.
